# Generated by Django 5.2 on 2025-04-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_workshop"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profession",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Профессия"
            ),
        ),
    ]
