# Generated by Django 5.2 on 2025-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_profession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="workshop",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Подразделение"
            ),
        ),
    ]
