# Generated by Django 5.2 on 2025-06-13 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="cat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categ",
                to="materials.categorymaterials",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to="uploads/", verbose_name="Файл"),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="type_file",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Файл или видео"
            ),
        ),
    ]
