# Generated by Django 5.2 on 2025-05-07 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название категории"),
                ),
                ("slug", models.SlugField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={"verbose_name": "File", "verbose_name_plural": "Files"},
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="type_file",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="file or video"
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="cat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categ",
                to="materials.categorymaterials",
            ),
        ),
    ]
