# Generated by Django 5.2 on 2025-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0002_categorymaterials_alter_uploadedfile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymaterials",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="category/%Y/%m/%d",
                verbose_name="Фото",
            ),
        ),
    ]
