# Generated by Django 5.2 on 2025-04-25 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mashine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='answersuser',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='questions',
            name='mash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plumber.mashine'),
        ),
    ]
