# Generated by Django 3.2.25 on 2025-05-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='professions/%Y/%m/%d', verbose_name='IMAGE'),
        ),
    ]
