# Generated by Django 5.2 on 2025-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
