# Generated by Django 5.2 on 2025-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0002_answers_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
