# Generated by Django 3.2.25 on 2025-05-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0002_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashine',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plumber.professions'),
        ),
    ]
