# Generated by Django 5.2 on 2025-04-25 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0002_mashine_alter_answersuser_answer_questions_mash'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='mash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plumber.mashine'),
        ),
    ]
