# Generated by Django 5.2 on 2025-06-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plumber", "0002_professions_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="answersuser",
            name="otvet",
            field=models.TextField(blank=True, null=True),
        ),
    ]
