# Generated by Django 5.2 on 2025-04-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0003_answers_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer_num', models.IntegerField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
