# Generated by Django 3.2.25 on 2025-05-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0003_auto_20250514_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professions',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
